language: node_js

node_js:
  - "10.13.0"


matrix:
  include:
  - name: "Windows"
    os: windows
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
  - name: "MacOS"
    os: osx


install:
  - cd test
  - npm i
